---
- name: ANSISTRANO | Package
  hosts: localhost
  connection: local

  pre_tasks:
    - name: ANSISTRANO | Set git tag if defined in ansible command
      set_fact:
        ansistrano_git_branch: "{{ tag }}"
      when: tag is defined

  roles:
    - { role: ansistrano-package }

- name: ANSISTRANO | Deploy
  hosts: all
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
