version: "3.3"

services:
  deploy:
    build: .
    container_name: "myproject_deploy"
    volumes:
      - cache:/home/deploy/.ansistrano
    tty: true
    stdin_open: true

volumes:
  cache:
    driver: "local"