version: "2"

services:
  deploy:
    build: .
    container_name: "deploy"
    environment:
      - "SSH_AUTH_SOCK=/ssh-agent"
    volumes:
      - ".:/deploy"
      - "${SSH_AUTH_SOCK}:/ssh-agent"
      - "${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts"
      - "${HOME}/.gitconfig:/root/.gitconfig"
      - "${HOME}/.bashrc:/root/.bashrc"
    hostname: deploy
    tty: true
    stdin_open: true
